# DJIA files
inputFileDJIA: '../Datasets/DJIA/{}.csv'
outputFileDJIA: '../Datasets/DJIA/new{}.csv'

# Twitter files
inputFileTwitter: '../Datasets/Companies 2017/{}.csv'
intermediateFileTwitter: '../Datasets/New Companies/old{}.csv'
outputFileTwitter: '../Datasets/New Companies/{}.csv'

# Files to be saved
grangerResultsPath: '../Results/grangerResult'


# Do Preprocessing
doTwitterPreprocessing: True
doDJIAPreprocessing: True

# Plot Graphs
PlotGraphs: True

# ZScaling and threshold
ZScaling: 7.5
threshold: 0.1